### ISSUE TITLE
There is an Error creating mysite.dev file

### ISSUE THREAD

**Issue by sendyputra** [RoverWire/virtualhost#11]
i have error report like this :

<pre>
# sudo virtualhost create mysite.dev
sudo: virtualhost: command not found
# virtualhost create mysite.dev
Added content to /var/www/mysitedev/phpinfo.php
/usr/local/bin/virtualhost: line 81: /etc/apache2/sites-available/mysite.dev.conf: No such file or directory
There is an ERROR creating mysite.dev file
</pre>

**Comment by RoverWire** [comment]
which ubuntu version are you using? To try to replicate the error.

**Comment by RoverWire** [comment]
Already tested and no problem was found. Are you still have the issue?
