### ISSUE TITLE
Change default /var/www

### ISSUE THREAD

**Issue by ljuboja** [RoverWire/virtualhost#14]
How to change default dir to something else ?

**Comment by RoverWire** [comment]
You can set the variable at the top of script and add permisions to www group to the new destination folder.

**Comment by bobbyqiz448** [comment]
How to run a folder in desktop on virtual host?

**Comment by bobbyqiz448** [comment]
is it possible?

**Comment by RoverWire** [comment]
Yes, you need to run this script with the absolute path to the desktop folder. I assume you are a linux user, because this does not work on windows.

**Comment by bobbyqiz448** [comment]
Sure. I am a linux user
