### ISSUE TITLE
var $sitesAvailabledomain not complete?

### ISSUE THREAD

**Issue by webghostx** [RoverWire/virtualhost#15]
is the variable $sitesAvailabledomain not complete at this point?

I had to change it to $sitesAvailable$domain.conf - so it works for me

https://github.com/RoverWire/virtualhost/blob/master/virtualhost.sh#L81

**Comment by RoverWire** [comment]
Yes, you can verify it on Line 14

https://github.com/RoverWire/virtualhost/blob/master/virtualhost.sh#L14
