### ISSUE TITLE
Fails to create subdirectory

### ISSUE THREAD

**Issue by bsiu** [RoverWire/virtualhost#18]
Thanks for this script. Very useful.

It fails if the parent directory of `$rootdir` does not exist. For example:

`sudo virtualhost.sh create laravel_domain laravel_domain/public`

will fail because directory `laravel_domain` does not exist. It is common for some frameworks like Laravel to point the virtualhosts to a subdirectory.

To fix, change the mkdir command from `mkdir` to `mkdir -p`.

**Comment by RoverWire** [comment]
I think you don't get it how the script works, you don't use an domain path, you must use the path that is relative to $rootdir or absolute path if begins with /.

i.e.  if you have a laravel-project folder on /var/www, you must use

```$ sudo virtualhost create laraveldomain.com laravel-project/public```

if you pass the path after the domain, the script won't create the folder, it assumes that already exists.

**Comment by RoverWire** [comment]
And if you have your laravel-project out of /var/www (or wherever your rootdir is), example, home folder

```sudo virtualhost.sh create laravel_domain /home/roverwire/laravel_domain/public```

and that's it!
