### ISSUE TITLE
Feature request: add entry to /etc/hosts

### ISSUE THREAD

**Issue by bsiu** [RoverWire/virtualhost#19]
I suggest adding a command that modifies `/etc/hosts` to include the newly created domain as a fake host.

`virtualhost.sh hosts laravel_domain 127.0.0.1`

That would add the following line to /etc/hosts:

`127.0.0.1    laravel_domain`

Great work. Thanks.

**Comment by RoverWire** [comment]
That is already implemented, when you create a virtual host domain, is added to /etc/hosts.

https://github.com/RoverWire/virtualhost/blob/master/virtualhost.sh#L97

**Comment by bsiu** [comment]
Duh. Was using an old version of your script. Thanks.
