### ISSUE TITLE
Error when run from crontab

### ISSUE THREAD

**Issue by mobisync** [RoverWire/virtualhost#22]
Hi,

i was run this bash file from crontab but its not working in this line
`a2ensite $domain`

when i run the shell script by root from terminal its working

Cheers

**Comment by RoverWire** [comment]
Did you check if crontab have permission to manage services?

**Comment by biperch** [comment]
Use  sudo

**Comment by RoverWire** [comment]
that is odd, already made a test on 14.04 without problem, why do you use crontab to create local virtual hosts?
