### ISSUE TITLE
Option to set set the owner and group

### ISSUE THREAD

**Issue by invasi0n** [RoverWire/virtualhost#25]
By default the owner and group are both set to root. Can you please add an option to set the owner and group?
Something like `sudo virtualhost [create] [domain] [optional host_dir] [owner] [group]` I think would be great.

Thank you!

**Comment by RoverWire** [comment]
Hi, sorry for the delay. Not sure about your request, since if you add your user to www-data group, it will work without problem.

**Comment by prashantnirgun** [comment]
Thanks for creating a wonderful shell script. Kndly add the example of how to use owner and group.
