### ISSUE TITLE
Problem with Virtualhost Nginx

### ISSUE THREAD

**Issue by endrureza** [RoverWire/virtualhost#29]
Well, recently i installed your bash script in order to create nginx VH. What works for me is this edited script

https://gist.github.com/endrureza/df7c0971e429be5a3c68ac9821f463d0

but whenever i created freshly from your script it doesn't work. let's say nginx return 502 bad gateway, below the not working code 

https://gist.github.com/endrureza/dd206e48112daa0befa8667188981d0f

what did i miss? is that related to new configuration of nginx somehow?

**Comment by RoverWire** [comment]
Probably you are right about new nginx configuration, I will test to get sure and fix it is that is the case.
