### ISSUE TITLE
Add user account

### ISSUE THREAD

**Issue by jaccovdwijgaart** [RoverWire/virtualhost#30]
Thank you for this script, you helped me and i am sure of, a lot of others out.
But, i think it is a good idea to add this:

After the script has created a new virtual host and its folders like this: 
`sudo ./virtualhost.sh create example.com`

> Succes!
> 
> Directory made in /var/www/examplecom

That after all of this, it asks you if you want to add a user to this folder like this:

> Do you want to make an user for this domain? y/n

`y`

`sudo adduser $2`
`sudo usermod  -d $3/$2  $2`

`sudo chroot the webfolder (/var/www/examplecom) and give the right permssions to the corresponding user (examplecom)`
USERMOD COMMAND: sudo usermod  -d new_home_dir  username

Something like this ^ I have no idea to make this myself but i think it would be a great addition to your script!

EDIT:
The main reason i want to use it for is for FTP users, so that when i have an chroot FTP server running, the directory of the user would then be /var/www/examplecom. This is very usefull for people that are using wordpress or just to add and remove files from their part of the server (their web folder)

**Comment by RoverWire** [comment]
I think this is related to #25 and I thinking to add a feature to especify an owner of the folder, but not sure about your request to ask for user creation, I think is a particular problem, I can help you with that, but not sure to include it as a feature for release.
