### ISSUE TITLE
Feature request domain directory structure domain/public_html

### ISSUE THREAD

**Issue by prashantnirgun** [RoverWire/virtualhost#31]
Hi 

Just feature request I am using Ubuntu 16 and it has following structure 
/var/www/html and the script create folder in /var/www ie not inside the www folder. I need to create public_html folder inside the Virtual host. I give following command.

sudo virtualhost create dev.local /var/www/html/dev.local/public_html prashant www-data
# it gives the error

mkdir: cannot create directory ‘/var/www/html/dev.local/public_html’: No such file or directory
chmod: cannot access '/var/www/html/dev.local/public_html': No such file or directory
/usr/local/bin/virtualhost: line 61: /var/www/html/dev.local/public_html/phpinfo.php: No such file or directory
# ERROR: Not able to write in file /var/www/html/dev.local/public_html/phpinfo.php. Please check permissions.

**Comment by rafa-acioly** [comment]
the script create the folder without the dot `dev.local` (devlocal), so, when you pass the path in `create` option you should use;

`sudo virtualhost create dev.local var/www/html/devlocal/public_html`

can you try this way?

**Comment by prashantnirgun** [comment]
still this get fails (mkdir * chown fails even though running with sudo)

sudo virtualhost create theme.local /var/www/html/themelocal/public_html
mkdir: cannot create directory ‘/var/www/html/themelocal/public_html’: No such file or directory
chmod: cannot access '/var/www/html/themelocal/public_html': No such file or directory
/usr/local/bin/virtualhost: line 61: /var/www/html/themelocal/public_html/phpinfo.php: No such file or directory
ERROR: Not able to write in file /var/www/html/themelocal/public_html/phpinfo.php. Please check permissions

**Comment by prashantnirgun** [comment]
I first create directory using sudo mkdir -p  /var/www/html/theme.local/public_html
and then it works.
