### ISSUE TITLE
Adding the host to windows host file

### ISSUE THREAD

**Issue by cAstraea** [RoverWire/virtualhost#33]
Hello, 
Added the same check to add the new domain to windows host file , running on the windows bash with a small caveat. The window bash needs to be run as Administrator for it to have write access to the file.

                if ! echo "127.0.0.1    $domain" >> /mnt/c/Windows/System32/drivers/etc/hosts
                then
                        echo $"ERROR: Not able to write in windows hosts file"
                        exit;
                else
                        echo -e $"Host added to windows hosts file \n"
                fi

**Comment by jammer99** [comment]
@cAstraea you can change the permissions on `C:\Windows\System32\drivers\etc\Hosts` to allow access to all users, then run as Admin is not required

**Comment by RoverWire** [comment]
This was solved on #40
