### ISSUE TITLE
Variable overwrite $userDir$rootDir

### ISSUE THREAD

**Issue by ezerw** [RoverWire/virtualhost#35]
Hi, just trying to use your script to save some time creating virtualhost on a mac.

I found that the line 40 is overwriting the rootDir variable passed as 3rd parameter and getting error when it tries to create the folder.

running: `sudo virtualhost create cms.dev cms`
got: `mkdir: /Users/eze/Projects/Web//Users/eze/Projects/Web: No such file or directory`

If I commented out that line all works, except that the nginx group on a mac is not `www-data`, it works with `staff` so I got `chown: www-data: illegal group name`. and that the domain is without the `.` (cms.dev -> cmsdev)

Maybe a top configurable variable like serverGroup or so will make it more flexible.

Thanks!

**Comment by RoverWire** [comment]
This script is not intended to be used on mac, just for Linux. probably would have another script for MacOS.
