### ISSUE TITLE
"Please check permissions" in NGINX version

### ISSUE THREAD

**Issue by TurningTide** [RoverWire/virtualhost#48]
There is a mistake on line 40 of nginx script.
firstly it concatenates userDir and rootDir, and after that it does it again in next blocks of code.

as result it tries to create directory like "/var/www//var/www/domain.com" which is not right.
simply remove "rootDir=$userDir$rootDir" on line 40 and you are good.

**Comment by blankse** [comment]
Here is a PR for this issue: https://github.com/RoverWire/virtualhost/pull/44

**Comment by RoverWire** [comment]
Resolved with #44
