### ISSUE TITLE
There is an ERROR creating phyo.test file

### ISSUE THREAD

**Issue by ARKAR-PHYO** [RoverWire/virtualhost#58]
I installed and run exactly but those errors show up ... 
`/usr/local/bin/virtualhost: line 89: /etc/apache2/sites-available/phyo.test.conf: No such file or directory
There is an ERROR creating phyo.test file` 
How can I solve it ? Please Help me ..

**Comment by RoverWire** [comment]
There is no `phyo.test`, which version of script and operating system are you using?
