### ISSUE TITLE
Error when creating new virtualhost

### ISSUE THREAD

**Issue by dandyrow** [RoverWire/virtualhost#60]
When I try and create a new virtualhost with this command: `sudo virtualhost create dan.test dan` I get the following errors:

```
/usr/local/bin/virtualhost: 31: [: dan.test: unexpected operator
/usr/local/bin/virtualhost: 37: [: dan: unexpected operator
/usr/local/bin/virtualhost: 42: /usr/local/bin/virtualhost: [[: not found
/usr/local/bin/virtualhost: 48: [: create: unexpected operator
-e $This domain does not exist.
Please try another one
```

The virtualhost is not created. I have tried this a few times with a few different commands and it still doesn't work.

**Comment by RoverWire** [comment]
which script are you using? Could you give me more details about your operating system?

**Comment by lulu5-c** [comment]
sudo sh /home/houngbemey/virtualhost/virtualhost.sh create smartenterprise.site
/home/houngbemey/virtualhost/virtualhost.sh: 30: [: smartenterprise.site: unexpected operator
/home/houngbemey/virtualhost/virtualhost.sh: 36: [: unexpected operator
/home/houngbemey/virtualhost/virtualhost.sh: 41: [[: not found
/home/houngbemey/virtualhost/virtualhost.sh: 47: [: create: unexpected operator
-e $This domain does not exist.
Please try another one
### ### Good evening to all. Please help me, I have encountered the same error, I have cloned your project, followed your instructions but I encounter this error. 
My operating system is ubuntu 20.04
