### ISSUE TITLE
Lets Encrypt

### ISSUE THREAD

**Issue by all12jus** [RoverWire/virtualhost#64]
Any interest in adding support for automating the adding of ssl to domains when they get added. Along with adding the auto updating the ssl cert with graceful reloading of the server?

**Comment by RoverWire** [comment]
Well, this script was intended for dev enviroment. I think is not suitable use it for production, because each server would have another custom settings.

**Comment by JamesThanna** [comment]
Just run Certbot and this will pick up the Vhosts and configure based on that. It's a matter of one more command to complete the SSL install and it's auto configures it.
